# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/gatcadnet',
                'doc_host': 'https://niyazikemer.github.io',
                'git_url': 'https://github.com/niyazikemer/gatcadnet',
                'lib_path': 'gatcadnet'},
  'syms': {'gatcadnet.core': {}}}
